/**
 * BEING - PENGEMBANGAN DIRI • BACKEND v2.3 • ADMIN TERPADU
 * Multi program • Gratis/Berbayar • Verifikasi Pembayaran • Filter Ekosistem
 */
const CONFIG={
  SPREADSHEET_ID:'1jzx2Sna9p0a3wbhxAcqubxqGBcHEo585Ku34AInfG14',
  ADMIN_KEY:'being123456',
  WEB_BASE_URL:'https://bangdir.beingpsikologi.com/',
  ADMIN_EMAIL:'adminbeing@gmail.com',
  PAYMENT_BANK_NAME:'BANK BEING',
  PAYMENT_ACCOUNT_NUMBER:'0000000000',
  PAYMENT_ACCOUNT_HOLDER:'BEING BIRO PSIKOLOGI',
  PAYMENT_QRIS_URL:'',
  PAYMENT_FOLDER_ID:''
};
const SHEETS={
 PROGRAM:['ProgramID','Nama','Kategori','Deskripsi','Status','PricingType','Price','TanggalMulai','TanggalAkhir','Tanggal','MediaURL','MediaType'],
 PESERTA:['PesertaID','ProgramID','Nama','Email','WA','Instansi','Catatan','Status','PaymentStatus','AccessToken','TanggalDaftar','TanggalAktif'],
 SESI:['SesiID','ProgramID','Judul','Deskripsi','TanggalSesi','JamSesi','ZoomURL','ZoomAktif','Status','Tanggal'],
 MATERI:['MateriID','ProgramID','SesiID','Judul','Deskripsi','Link','Status','Tanggal'],
 PEMBAYARAN:['PaymentID','PesertaID','ProgramID','Nama','Email','Amount','ProofURL','Status','TanggalKirim','TanggalVerifikasi','Catatan'],
 KONTAK:['ContactID','Nama','Email','WA','Instansi','Sumber','PertamaMasuk','TerakhirAktif','TotalInteraksi','ProgramIDs','FormulirIDs']
};
function setupBeingLite(){const ss=SpreadsheetApp.openById(CONFIG.SPREADSHEET_ID);Object.keys(SHEETS).forEach(name=>{let sh=ss.getSheetByName(name);if(!sh)sh=ss.insertSheet(name);ensureHeaders_(sh,SHEETS[name])});return'Setup v2.2 selesai.'}
function setupBeingSederhana(){return setupBeingLite()}
function ensureHeaders_(sh,required){if(sh.getLastRow()===0){sh.getRange(1,1,1,required.length).setValues([required]);sh.setFrozenRows(1);return}const current=sh.getRange(1,1,1,Math.max(sh.getLastColumn(),1)).getValues()[0].map(v=>String(v).trim());required.forEach(h=>{if(!current.includes(h)){sh.getRange(1,sh.getLastColumn()+1).setValue(h);current.push(h)}});sh.setFrozenRows(1)}
function out(o){return ContentService.createTextOutput(JSON.stringify(o)).setMimeType(ContentService.MimeType.JSON)}
function ss_(){return SpreadsheetApp.openById(CONFIG.SPREADSHEET_ID)}
function sh_(n){const s=ss_().getSheetByName(n);if(!s)throw new Error('Sheet '+n+' belum ada. Jalankan setupBeingLite().');return s}
function rows_(n){const v=sh_(n).getDataRange().getValues();if(v.length<2)return[];const h=v.shift().map(x=>String(x).trim());return v.filter(r=>r.some(x=>x!==''&&x!==null)).map(r=>Object.fromEntries(h.map((x,i)=>[x,r[i]])))}
function appendObject_(n,o){const s=sh_(n),h=s.getRange(1,1,1,s.getLastColumn()).getValues()[0].map(x=>String(x).trim());s.appendRow(h.map(k=>Object.prototype.hasOwnProperty.call(o,k)?o[k]:''))}
function headerMap_(s){const h=s.getRange(1,1,1,s.getLastColumn()).getValues()[0],m={};h.forEach((x,i)=>m[String(x).trim()]=i+1);return m}
function requireAdmin_(k){if(!k||String(k)!==String(CONFIG.ADMIN_KEY))throw new Error('Kunci admin tidak valid.')}
function id_(p){return p+'-'+Utilities.getUuid().replace(/-/g,'').slice(0,10).toUpperCase()}
function token_(){return'BEING-'+Utilities.getUuid().replace(/-/g,'').slice(0,8).toUpperCase()}
function now_(){return new Date()}
function dateOnly_(v){if(!v)return'';const d=v instanceof Date?v:new Date(v);if(isNaN(d.getTime()))return String(v||'');return Utilities.formatDate(d,Session.getScriptTimeZone()||'Asia/Jakarta','yyyy-MM-dd')}
function hasEnded_(v){const e=dateOnly_(v);if(!e)return false;const t=Utilities.formatDate(new Date(),Session.getScriptTimeZone()||'Asia/Jakarta','yyyy-MM-dd');return e<t}
function normalizeCategory_(v){const r=String(v||'').trim().toUpperCase();if(r==='BOOT CAMP')return'BOOTCAMP';if(r==='SERTIFIKASI'||r==='BNSP')return'SERTIFIKASI BNSP';if(['SHARING KNOWLEDGE','BOOTCAMP','SERTIFIKASI BNSP'].includes(r))return r;return'SHARING KNOWLEDGE'}
function pricing_(v){return String(v||'GRATIS').trim().toUpperCase()==='BERBAYAR'?'BERBAYAR':'GRATIS'}
function inferMediaType_(url,exp){const t=String(exp||'').trim().toUpperCase();if(t)return t;const u=String(url||'').toLowerCase();if(/\.(jpg|jpeg|png|webp)(\?|$)/.test(u))return'IMAGE';if(/\.pdf(\?|$)/.test(u))return'PDF';return u?'LINK':''}

function doGet(e){try{const p=e&&e.parameter?e.parameter:{},a=p.action||'';if(a==='ping')return out({ok:true,message:'BEING v2.2 aktif'});if(a==='publicPrograms')return out({ok:true,data:getPublicPrograms_()});if(a==='portal')return out(getPortal_(p.token||'',p.programId||''));requireAdmin_(p.adminKey);if(a==='adminPrograms')return out({ok:true,data:getPrograms_()});if(a==='adminParticipants')return out({ok:true,data:getParticipants_()});if(a==='adminMaterials')return out({ok:true,data:getMaterials_()});if(a==='adminSessions')return out({ok:true,data:getSessions_()});if(a==='adminPayments')return out({ok:true,data:getPayments_()});if(a==='adminContacts')return out({ok:true,data:getContacts_()});return out({ok:false,message:'Action tidak dikenal'})}catch(err){return out({ok:false,message:String(err.message||err)})}}
function doPost(e){try{let b={};if(e&&e.parameter&&Object.keys(e.parameter).length)b=e.parameter;else if(e&&e.postData&&e.postData.contents){try{b=JSON.parse(e.postData.contents)}catch(_){}}const a=b.action||'';if(a==='register')return out(register_(b));if(a==='submitPayment')return out(submitPayment_(b));requireAdmin_(b.adminKey);
 const map={createProgram:createProgram_,setProgramStatus:setProgramStatus_,setProgramMedia:setProgramMedia_,deleteProgram:deleteProgram_,createMaterial:createMaterial_,setMaterialStatus:setMaterialStatus_,deleteMaterial:deleteMaterial_,createSession:createSession_,setSessionStatus:setSessionStatus_,toggleSessionZoom:toggleSessionZoom_,deleteSession:deleteSession_,deleteParticipant:deleteParticipant_,approvePayment:approvePayment_,rejectPayment:rejectPayment_,deletePayment:deletePayment_,sendAccessEmail:sendAccessEmailAction_,syncContacts:syncParticipantsToContacts_};
 if(map[a])return out(map[a](b));return out({ok:false,message:'Action tidak dikenal'})}catch(err){return out({ok:false,message:String(err.message||err)})}}

function getPrograms_(){return rows_('PROGRAM').map(r=>({programId:String(r.ProgramID||''),nama:String(r.Nama||''),kategori:normalizeCategory_(r.Kategori),deskripsi:String(r.Deskripsi||''),status:String(r.Status||'').trim().toUpperCase(),pricingType:pricing_(r.PricingType),price:Number(r.Price||0),tanggalMulai:dateOnly_(r.TanggalMulai),tanggalAkhir:dateOnly_(r.TanggalAkhir),selesai:hasEnded_(r.TanggalAkhir),tanggal:dateOnly_(r.Tanggal),mediaUrl:String(r.MediaURL||''),mediaType:inferMediaType_(r.MediaURL,r.MediaType)}))}
function getPublicPrograms_(){return getPrograms_().filter(p=>p.status==='BUKA'&&!p.selesai)}
function createProgram_(b){const nama=String(b.nama||'').trim();if(!nama)return{ok:false,message:'Nama program wajib diisi.'};const type=pricing_(b.pricingType),price=type==='GRATIS'?0:Number(b.price||0);if(type==='BERBAYAR'&&price<=0)return{ok:false,message:'Program berbayar harus memiliki harga.'};const tm=String(b.tanggalMulai||''),ta=String(b.tanggalAkhir||'');if(tm&&ta&&ta<tm)return{ok:false,message:'Tanggal akhir tidak boleh lebih awal dari tanggal mulai.'};appendObject_('PROGRAM',{ProgramID:id_('PRG'),Nama:nama,Kategori:normalizeCategory_(b.kategori),Deskripsi:String(b.deskripsi||'').trim(),Status:String(b.status||'BUKA').toUpperCase(),PricingType:type,Price:price,TanggalMulai:tm,TanggalAkhir:ta,Tanggal:now_(),MediaURL:String(b.mediaUrl||'').trim(),MediaType:inferMediaType_(b.mediaUrl,b.mediaType)});return{ok:true,message:'Program berhasil dibuat.'}}
function setProgramStatus_(b){updateById_('PROGRAM','ProgramID',b.programId,'Status',String(b.status||'').toUpperCase());return{ok:true,message:'Status program diperbarui.'}}
function setProgramMedia_(b){updateById_('PROGRAM','ProgramID',b.programId,'MediaURL',String(b.mediaUrl||''));updateById_('PROGRAM','ProgramID',b.programId,'MediaType',inferMediaType_(b.mediaUrl,b.mediaType));return{ok:true,message:'Media program diperbarui.'}}
function deleteProgram_(b){const id=String(b.programId||'');const c1=rows_('PESERTA').filter(r=>String(r.ProgramID)===id).length,c2=rows_('MATERI').filter(r=>String(r.ProgramID)===id).length,c3=rows_('SESI').filter(r=>String(r.ProgramID)===id).length,c4=rows_('PEMBAYARAN').filter(r=>String(r.ProgramID)===id).length;if(c1+c2+c3+c4>0)return{ok:false,message:`Program masih memiliki ${c1} peserta, ${c2} materi, ${c3} sesi, ${c4} pembayaran. Hapus data terkait atau tutup program.`};return deleteById_('PROGRAM','ProgramID',id)?{ok:true,message:'Program dihapus.'}:{ok:false,message:'Program tidak ditemukan.'}}

function existingTokenForEmail_(email){const e=String(email||'').trim().toLowerCase();const r=rows_('PESERTA').find(x=>String(x.Email||'').trim().toLowerCase()===e&&String(x.AccessToken||'').trim());return r?String(r.AccessToken):''}
function register_(b){
 const programId=String(b.programId||''),nama=String(b.nama||'').trim(),email=String(b.email||'').trim(),wa=String(b.wa||'').trim();
 if(!programId||!nama||!email||!wa)return{ok:false,message:'Data pendaftaran belum lengkap.'};
 const program=getPublicPrograms_().find(p=>p.programId===programId);if(!program)return{ok:false,message:'Program tidak tersedia atau periode sudah berakhir.'};
 const dup=rows_('PESERTA').find(r=>String(r.ProgramID)===programId&&String(r.Email||'').toLowerCase()===email.toLowerCase()&&!['DITOLAK','DIBATALKAN'].includes(String(r.Status||'').toUpperCase()));if(dup)return{ok:false,message:'Email ini sudah terdaftar pada program tersebut.'};
 const token=existingTokenForEmail_(email)||token_(),free=program.pricingType==='GRATIS',pid=id_('PST');
 appendObject_('PESERTA',{PesertaID:pid,ProgramID:programId,Nama:nama,Email:email,WA:wa,Instansi:String(b.institution||''),Catatan:String(b.note||''),Status:free?'AKTIF':'MENUNGGU_BAYAR',PaymentStatus:free?'TIDAK_PERLU':'BELUM_BAYAR',AccessToken:token,TanggalDaftar:now_(),TanggalAktif:free?now_():''});
 upsertContact_({nama,email,wa,instansi:String(b.institution||''),sumber:'PENGEMBANGAN DIRI',programId});
 const peserta=getParticipants_().find(p=>p.pesertaId===pid);
 if(free){try{sendAccessEmail_(peserta)}catch(err){}return{ok:true,pricingType:'GRATIS',pesertaId:pid,programNama:program.nama,accessToken:token,accessUrl:accessUrl_(token),message:'Pendaftaran aktif dan email akses dikirim.'}}
 try{sendPaymentInstructionEmail_(peserta,program)}catch(err){}
 return{ok:true,pricingType:'BERBAYAR',pesertaId:pid,programNama:program.nama,amountDue:program.price,payment:paymentConfig_(),message:'Pendaftaran diterima. Silakan lakukan pembayaran dan upload bukti.'}
}
function paymentConfig_(){return{bankName:CONFIG.PAYMENT_BANK_NAME,accountNumber:CONFIG.PAYMENT_ACCOUNT_NUMBER,accountHolder:CONFIG.PAYMENT_ACCOUNT_HOLDER,qrisUrl:CONFIG.PAYMENT_QRIS_URL}}
function sendPaymentInstructionEmail_(p,program){const q=paymentConfig_();MailApp.sendEmail({to:p.email,name:'BEING Biro Psikologi',replyTo:CONFIG.ADMIN_EMAIL,subject:'Instruksi Pembayaran - '+program.nama,htmlBody:`<p>Halo <b>${p.nama}</b>,</p><p>Pendaftaran program <b>${program.nama}</b> telah diterima.</p><p>Nominal: <b>Rp ${Number(program.price).toLocaleString('id-ID')}</b><br>Bank: <b>${q.bankName}</b><br>No. Rekening: <b>${q.accountNumber}</b><br>Atas nama: <b>${q.accountHolder}</b></p>${q.qrisUrl?`<p><a href="${q.qrisUrl}">Buka QRIS</a></p>`:''}<p>Setelah pembayaran, upload bukti pada halaman pendaftaran. Akses MyBeing dikirim setelah pembayaran diverifikasi Studio.</p><p>Salam,<br>BEING Biro Psikologi<br>${CONFIG.ADMIN_EMAIL}</p>`})}
function saveProof_(data,name,mime,pid){const m=String(data||'').match(/^data:([^;]+);base64,(.+)$/);if(!m)throw new Error('Format file tidak valid.');const bytes=Utilities.base64Decode(m[2]);if(bytes.length>2*1024*1024)throw new Error('Ukuran file maksimal 2 MB.');const blob=Utilities.newBlob(bytes,mime||m[1],pid+' - '+String(name||'bukti'));const folder=CONFIG.PAYMENT_FOLDER_ID?DriveApp.getFolderById(CONFIG.PAYMENT_FOLDER_ID):DriveApp.getRootFolder();const f=folder.createFile(blob);try{f.setSharing(DriveApp.Access.ANYONE_WITH_LINK,DriveApp.Permission.VIEW)}catch(_){}return f.getUrl()}
function submitPayment_(b){const pid=String(b.pesertaId||''),p=getParticipants_().find(x=>x.pesertaId===pid);if(!p)return{ok:false,message:'Pendaftaran tidak ditemukan.'};if(p.pricingType!=='BERBAYAR')return{ok:false,message:'Program ini tidak memerlukan pembayaran.'};if(p.status==='AKTIF')return{ok:false,message:'Program sudah aktif.'};const url=saveProof_(b.fileData,b.fileName,b.mimeType,pid);appendObject_('PEMBAYARAN',{PaymentID:id_('PAY'),PesertaID:pid,ProgramID:p.programId,Nama:p.nama,Email:p.email,Amount:p.price,ProofURL:url,Status:'MENUNGGU_VERIFIKASI',TanggalKirim:now_(),TanggalVerifikasi:'',Catatan:''});updateById_('PESERTA','PesertaID',pid,'Status','MENUNGGU_VERIFIKASI');updateById_('PESERTA','PesertaID',pid,'PaymentStatus','MENUNGGU_VERIFIKASI');return{ok:true,message:'Bukti pembayaran berhasil dikirim.'}}

function getParticipants_(){const pm=Object.fromEntries(getPrograms_().map(p=>[p.programId,p]));return rows_('PESERTA').map(r=>{const p=pm[String(r.ProgramID)]||{};return{pesertaId:String(r.PesertaID||''),programId:String(r.ProgramID||''),programNama:p.nama||'-',kategori:p.kategori||'-',pricingType:p.pricingType||'GRATIS',price:Number(p.price||0),nama:String(r.Nama||''),email:String(r.Email||''),wa:String(r.WA||''),institution:String(r.Instansi||''),note:String(r.Catatan||''),status:String(r.Status||'').toUpperCase(),paymentStatus:String(r.PaymentStatus||''),accessToken:String(r.AccessToken||''),tanggalDaftar:dateOnly_(r.TanggalDaftar),tanggalAktif:dateOnly_(r.TanggalAktif)}}).reverse()}
function deleteParticipant_(b){const id=String(b.pesertaId||'');rows_('PEMBAYARAN').filter(r=>String(r.PesertaID)===id).forEach(r=>deleteById_('PEMBAYARAN','PaymentID',r.PaymentID));return deleteById_('PESERTA','PesertaID',id)?{ok:true,message:'Data peserta dan pembayaran terkait dihapus.'}:{ok:false,message:'Peserta tidak ditemukan.'}}

function getPayments_(){const pm=Object.fromEntries(getPrograms_().map(p=>[p.programId,p]));return rows_('PEMBAYARAN').map(r=>{const p=pm[String(r.ProgramID)]||{};return{paymentId:String(r.PaymentID||''),pesertaId:String(r.PesertaID||''),programId:String(r.ProgramID||''),programNama:p.nama||'-',kategori:p.kategori||'-',nama:String(r.Nama||''),email:String(r.Email||''),amount:Number(r.Amount||0),proofUrl:String(r.ProofURL||''),status:String(r.Status||'').toUpperCase(),tanggalKirim:dateOnly_(r.TanggalKirim),tanggalVerifikasi:dateOnly_(r.TanggalVerifikasi),catatan:String(r.Catatan||'')}}).reverse()}
function approvePayment_(b){const id=String(b.paymentId||''),pay=getPayments_().find(x=>x.paymentId===id);if(!pay)return{ok:false,message:'Pembayaran tidak ditemukan.'};if(pay.status!=='MENUNGGU_VERIFIKASI')return{ok:false,message:'Pembayaran ini sudah diproses.'};updateById_('PEMBAYARAN','PaymentID',id,'Status','LUNAS');updateById_('PEMBAYARAN','PaymentID',id,'TanggalVerifikasi',now_());updateById_('PESERTA','PesertaID',pay.pesertaId,'Status','AKTIF');updateById_('PESERTA','PesertaID',pay.pesertaId,'PaymentStatus','LUNAS');updateById_('PESERTA','PesertaID',pay.pesertaId,'TanggalAktif',now_());const p=getParticipants_().find(x=>x.pesertaId===pay.pesertaId);try{sendAccessEmail_(p)}catch(err){return{ok:true,message:'Pembayaran LUNAS dan peserta aktif, tetapi email gagal: '+String(err.message||err)}}return{ok:true,message:'Pembayaran LUNAS, peserta aktif, dan email akses terkirim.'}}
function rejectPayment_(b){const id=String(b.paymentId||''),pay=getPayments_().find(x=>x.paymentId===id);if(!pay)return{ok:false,message:'Pembayaran tidak ditemukan.'};updateById_('PEMBAYARAN','PaymentID',id,'Status','DITOLAK');updateById_('PEMBAYARAN','PaymentID',id,'TanggalVerifikasi',now_());updateById_('PEMBAYARAN','PaymentID',id,'Catatan',String(b.note||''));updateById_('PESERTA','PesertaID',pay.pesertaId,'Status','BUKTI_DITOLAK');updateById_('PESERTA','PesertaID',pay.pesertaId,'PaymentStatus','DITOLAK');try{MailApp.sendEmail({to:pay.email,name:'BEING Biro Psikologi',replyTo:CONFIG.ADMIN_EMAIL,subject:'Verifikasi Pembayaran BEING',htmlBody:`<p>Halo <b>${pay.nama}</b>,</p><p>Bukti pembayaran belum dapat kami verifikasi.</p><p>Catatan: <b>${String(b.note||'Silakan upload bukti pembayaran yang sesuai.')}</b></p><p>Salam,<br>BEING Biro Psikologi</p>`})}catch(_){}return{ok:true,message:'Pembayaran ditolak dan peserta dapat mengirim bukti ulang.'}}
function deletePayment_(b){return deleteById_('PEMBAYARAN','PaymentID',String(b.paymentId||''))?{ok:true,message:'Riwayat pembayaran dihapus.'}:{ok:false,message:'Pembayaran tidak ditemukan.'}}

function accessUrl_(t){return String(CONFIG.WEB_BASE_URL||'').replace(/\/?$/,'/')+'akses.html?access='+encodeURIComponent(t)}
function sendAccessEmail_(p){if(!p||p.status!=='AKTIF'||!p.accessToken)throw new Error('Peserta belum aktif.');MailApp.sendEmail({to:p.email,name:'BEING Biro Psikologi',replyTo:CONFIG.ADMIN_EMAIL,subject:'Akses MyBeing - '+p.programNama,htmlBody:`<p>Halo <b>${p.nama}</b>,</p><p>Program <b>${p.programNama}</b> telah aktif.</p><p>Kode akses: <b style="font-size:20px">${p.accessToken}</b></p><p><a href="${accessUrl_(p.accessToken)}">Buka MyBeing</a></p><p>Kode yang sama dapat digunakan kembali untuk melihat pembaruan program Anda.</p><p>Salam,<br>BEING Biro Psikologi<br>${CONFIG.ADMIN_EMAIL}</p>`})}
function sendAccessEmailAction_(b){const p=getParticipants_().find(x=>x.pesertaId===String(b.pesertaId||''));if(!p)return{ok:false,message:'Peserta tidak ditemukan.'};sendAccessEmail_(p);return{ok:true,message:'Email akses berhasil dikirim.'}}

function createMaterial_(b){if(!b.programId||!b.judul||!b.link)return{ok:false,message:'Program, judul, dan link wajib diisi.'};appendObject_('MATERI',{MateriID:id_('MAT'),ProgramID:String(b.programId),SesiID:String(b.sesiId||''),Judul:String(b.judul||''),Deskripsi:String(b.deskripsi||''),Link:String(b.link||''),Status:String(b.status||'PUBLIKASI').toUpperCase(),Tanggal:now_()});return{ok:true,message:'Materi disimpan.'}}
function getMaterials_(){const pm=Object.fromEntries(getPrograms_().map(p=>[p.programId,p])),sm=Object.fromEntries(getSessions_().map(s=>[s.sesiId,s.judul]));return rows_('MATERI').map(r=>{const p=pm[String(r.ProgramID)]||{};return{materiId:String(r.MateriID||''),programId:String(r.ProgramID||''),programNama:p.nama||'-',kategori:p.kategori||'-',sesiId:String(r.SesiID||''),sesiNama:sm[String(r.SesiID)]||'',judul:String(r.Judul||''),deskripsi:String(r.Deskripsi||''),link:String(r.Link||''),status:String(r.Status||'').toUpperCase(),tanggal:dateOnly_(r.Tanggal)}}).reverse()}
function setMaterialStatus_(b){updateById_('MATERI','MateriID',b.materiId,'Status',String(b.status||'').toUpperCase());return{ok:true,message:'Status materi diperbarui.'}}
function deleteMaterial_(b){return deleteById_('MATERI','MateriID',String(b.materiId||''))?{ok:true,message:'Materi dihapus.'}:{ok:false,message:'Materi tidak ditemukan.'}}

function createSession_(b){if(!b.programId||!b.judul||!b.tanggalSesi)return{ok:false,message:'Program, judul, dan tanggal sesi wajib diisi.'};appendObject_('SESI',{SesiID:id_('SES'),ProgramID:String(b.programId),Judul:String(b.judul||''),Deskripsi:String(b.deskripsi||''),TanggalSesi:String(b.tanggalSesi||''),JamSesi:String(b.jamSesi||''),ZoomURL:String(b.zoomUrl||''),ZoomAktif:String(b.zoomAktif||'TIDAK').toUpperCase(),Status:String(b.status||'PUBLIKASI').toUpperCase(),Tanggal:now_()});return{ok:true,message:'Sesi disimpan.'}}
function getSessions_(){const pm=Object.fromEntries(getPrograms_().map(p=>[p.programId,p]));return rows_('SESI').map(r=>{const p=pm[String(r.ProgramID)]||{};return{sesiId:String(r.SesiID||''),programId:String(r.ProgramID||''),programNama:p.nama||'-',kategori:p.kategori||'-',judul:String(r.Judul||''),deskripsi:String(r.Deskripsi||''),tanggalSesi:dateOnly_(r.TanggalSesi),jamSesi:String(r.JamSesi||''),zoomUrl:String(r.ZoomURL||''),zoomAktif:String(r.ZoomAktif||'').toUpperCase()==='YA',status:String(r.Status||'').toUpperCase(),tanggal:dateOnly_(r.Tanggal)}}).sort((a,b)=>(a.tanggalSesi+' '+a.jamSesi).localeCompare(b.tanggalSesi+' '+b.jamSesi))}
function setSessionStatus_(b){updateById_('SESI','SesiID',b.sesiId,'Status',String(b.status||'').toUpperCase());return{ok:true,message:'Status sesi diperbarui.'}}
function toggleSessionZoom_(b){updateById_('SESI','SesiID',b.sesiId,'ZoomAktif',String(b.zoomAktif||'TIDAK').toUpperCase());return{ok:true,message:'Akses Zoom diperbarui.'}}
function deleteSession_(b){const id=String(b.sesiId||''),ms=sh_('MATERI'),map=headerMap_(ms);if(map.SesiID)for(let r=2;r<=ms.getLastRow();r++)if(String(ms.getRange(r,map.SesiID).getValue())===id)ms.getRange(r,map.SesiID).setValue('');return deleteById_('SESI','SesiID',id)?{ok:true,message:'Sesi dihapus. Materi terkait tetap menjadi materi umum.'}:{ok:false,message:'Sesi tidak ditemukan.'}}

function getPortal_(token,programId){const t=String(token||'').trim().toUpperCase();if(!t)return{ok:false,message:'Masukkan kode akses.'};const active=getParticipants_().filter(p=>p.status==='AKTIF'&&String(p.accessToken||'').toUpperCase()===t);if(!active.length)return{ok:false,message:'Kode akses tidak valid atau belum ada program aktif.'};const ids=[...new Set(active.map(p=>p.programId))],plist=getPrograms_().filter(p=>ids.includes(p.programId));const selected=plist.find(p=>p.programId===String(programId||''))||plist[0];const owner=active[0];return{ok:true,data:{peserta:{nama:owner.nama,email:owner.email,accessToken:owner.accessToken},programs:plist,program:selected,sesi:getSessions_().filter(s=>s.programId===selected.programId&&s.status==='PUBLIKASI'),materi:getMaterials_().filter(m=>m.programId===selected.programId&&m.status==='PUBLIKASI'),refreshedAt:new Date().toISOString()}}}

function normalizeEmail_(v){return String(v||'').trim().toLowerCase()}
function normalizeWA_(v){let r=String(v||'').replace(/\D/g,'');if(r.startsWith('0'))r='62'+r.slice(1);return r}
function mergePipe_(oldV,newV){return [...new Set((String(oldV||'')+'|'+String(newV||'')).split('|').map(x=>x.trim()).filter(Boolean))].join(' | ')}
function getContacts_(){return rows_('KONTAK').map(r=>({contactId:String(r.ContactID||''),nama:String(r.Nama||''),email:String(r.Email||''),wa:String(r.WA||''),instansi:String(r.Instansi||''),sumber:String(r.Sumber||''),pertamaMasuk:dateOnly_(r.PertamaMasuk),terakhirAktif:dateOnly_(r.TerakhirAktif),totalInteraksi:Number(r.TotalInteraksi||0),programIds:String(r.ProgramIDs||''),formulirIds:String(r.FormulirIDs||'')})).reverse()}
function upsertContact_(d){
 const email=normalizeEmail_(d.email),wa=normalizeWA_(d.wa),s=sh_('KONTAK'),m=headerMap_(s);let row=0;
 for(let r=2;r<=s.getLastRow();r++){const re=normalizeEmail_(s.getRange(r,m.Email).getValue()),rw=normalizeWA_(s.getRange(r,m.WA).getValue());if((email&&re===email)||(wa&&rw===wa)){row=r;break}}
 if(!row){appendObject_('KONTAK',{ContactID:id_('CNT'),Nama:String(d.nama||''),Email:String(d.email||''),WA:String(d.wa||''),Instansi:String(d.instansi||''),Sumber:String(d.sumber||''),PertamaMasuk:now_(),TerakhirAktif:now_(),TotalInteraksi:1,ProgramIDs:String(d.programId||''),FormulirIDs:String(d.formulirId||'')});return true}
 if(String(d.nama||'').trim())s.getRange(row,m.Nama).setValue(String(d.nama).trim());
 if(String(d.email||'').trim())s.getRange(row,m.Email).setValue(String(d.email).trim());
 if(String(d.wa||'').trim())s.getRange(row,m.WA).setValue(String(d.wa).trim());
 if(String(d.instansi||'').trim())s.getRange(row,m.Instansi).setValue(String(d.instansi).trim());
 s.getRange(row,m.Sumber).setValue(mergePipe_(s.getRange(row,m.Sumber).getValue(),d.sumber));
 if(d.programId)s.getRange(row,m.ProgramIDs).setValue(mergePipe_(s.getRange(row,m.ProgramIDs).getValue(),d.programId));
 if(d.formulirId)s.getRange(row,m.FormulirIDs).setValue(mergePipe_(s.getRange(row,m.FormulirIDs).getValue(),d.formulirId));
 s.getRange(row,m.TerakhirAktif).setValue(now_());s.getRange(row,m.TotalInteraksi).setValue(Number(s.getRange(row,m.TotalInteraksi).getValue()||0)+1);return true
}
function syncParticipantsToContacts_(){const peserta=rows_('PESERTA');peserta.forEach(r=>upsertContact_({nama:r.Nama,email:r.Email,wa:r.WA,instansi:r.Instansi,sumber:'PENGEMBANGAN DIRI',programId:r.ProgramID}));return{ok:true,message:peserta.length+' data peserta disinkronkan ke Database Kontak.'}}

function updateById_(sheetName,idHeader,idValue,targetHeader,newValue){const s=sh_(sheetName),m=headerMap_(s);if(!m[idHeader]||!m[targetHeader])throw new Error('Header sheet tidak lengkap.');for(let r=2;r<=s.getLastRow();r++)if(String(s.getRange(r,m[idHeader]).getValue())===String(idValue)){s.getRange(r,m[targetHeader]).setValue(newValue);return true}return false}
function deleteById_(sheetName,idHeader,idValue){const s=sh_(sheetName),m=headerMap_(s);if(!m[idHeader])throw new Error('Header '+idHeader+' tidak ditemukan.');for(let r=2;r<=s.getLastRow();r++)if(String(s.getRange(r,m[idHeader]).getValue())===String(idValue)){s.deleteRow(r);return true}return false}
